# Generated by Django 4.2 on 2023-04-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCertify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certificate',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
